spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:8888

spring.application.name=MSEnseignant4twin6

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

management.endpoints.web.exposure.include=refresh

welcome.message=Welcome to MSEnseignant4twin6 MS
