welcome.message=Welcome to MSEtudiant4twin6 MS
server.port=8093

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/school-realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/school-realm/protocol/openid-connect/certs}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:file:./Database/Data/etudiants_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=etudiants_user
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2
