welcome.message=Welcome to MSNotes4twin6 MS
server.port=8088
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/ms_notes

keycloak.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/school-realm}
keycloak.jwt-audience=${KEYCLOAK_JWT_AUDIENCE:account}
