spring.application.name=demoApiGateway
server.port=8080
#eureka
eureka.client.register-with-eureka=true
eureka.client.service-url[defaultZone]=http://eureka-server:8761/eureka
eureka.instance.hostname=api-gateway
eureka.instance.prefer-ip-address=false

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG
